import test from 'node:test';
import assert from 'node:assert/strict';
import { midiToHz, octavePartials, shepardWeights, missingFundamental, predictedProducts, wrap01, stereoAlternate } from '../src/audio/core.js';
import { advancePhase, clampLane, coherentRoutes, contradictionRoutes } from '../src/infinite-motion/core.js';

test('midiToHz anchors A4 and octave ratio', () => { assert.ok(Math.abs(midiToHz(69)-440)<1e-9); assert.ok(Math.abs(midiToHz(81)/midiToHz(69)-2)<1e-12); });
test('Shepard partials remain octave spaced and weights normalize',()=>{const p=octavePartials(220,6);for(let i=1;i<p.length;i++)assert.ok(Math.abs(p[i]/p[i-1]-2)<1e-12);const w=shepardWeights(p,880,1.25);assert.ok(w.every(Number.isFinite));assert.ok(Math.abs(Math.max(...w)-1)<1e-12)});
test('missing fundamental omits f0 and preserves harmonic multiples',()=>{const h=missingFundamental(100,2,6);assert.deepEqual(h.map(x=>x.frequency),[200,300,400,500,600]);assert.ok(!h.some(x=>x.frequency===100))});
test('combination product formulas are separated from primaries',()=>{const p=predictedProducts(700,900);assert.equal(p.difference,200);assert.equal(p.twoF1MinusF2,500);assert.equal(p.twoF2MinusF1,1100)});
test('wrap01 and motion advance wrap in both directions',()=>{assert.equal(wrap01(1.25),.25);assert.equal(wrap01(-.25),.75);assert.equal(advancePhase(.9,.3,1),.2);assert.equal(advancePhase(.1,-.3,1),.8)});
test('stereo alternation swaps high/low exactly',()=>{const ev=stereoAlternate(400,800,4);assert.deepEqual(ev.map(e=>[e.left,e.right]),[[400,800],[800,400],[400,800],[800,400]])});
test('motion lanes clamp and contradiction routes can oppose cues',()=>{assert.equal(clampLane(2),1);assert.equal(clampLane(-2),-1);const c=coherentRoutes(.6);assert.equal(c.pitch,.6);assert.equal(c.pan,.6);const x=contradictionRoutes({pitch:.7,pan:-.7,distance:1,spectrum:-1,tempo:-.5});assert.equal(x.pitch,.7);assert.equal(x.pan,-.7);assert.equal(x.tempo,-.5)});
test('continuous Shepard frame wraps with finite normalized gains',async()=>{const{shepardFrame}=await import('../src/audio/core.js');const a=shepardFrame(110,6,900,1.3,.99,1),b=shepardFrame(110,6,900,1.3,.01,1);assert.equal(a.length,6);assert.ok(a.every(x=>Number.isFinite(x.frequency)&&x.gain>=0&&x.gain<=1));assert.ok(Math.abs(Math.max(...a.map(x=>x.gain))-1)<1e-12);assert.ok(Math.abs(Math.max(...b.map(x=>x.gain))-1)<1e-12)});
test('Risset frame rate bank remains power-of-two related with normalized weights',async()=>{const{rissetFrame}=await import('../src/audio/core.js');const f=rissetFrame(90,5,.35,1);assert.equal(f.length,5);for(let i=1;i<f.length;i++)assert.ok(Math.abs(f[i].rate/f[i-1].rate-2)<1e-12);assert.ok(Math.abs(Math.max(...f.map(x=>x.gain))-1)<1e-12)});
test('scale stereo schedule crosses ascending and descending lines between ears',async()=>{const{scaleStereoEvents}=await import('../src/audio/core.js');const e=scaleStereoEvents(60,8);assert.equal(e.length,8);assert.equal(e[0].left,60);assert.equal(e[0].right,72);assert.equal(e[1].left,71);assert.equal(e[1].right,62)});
test('continuity cycle explicitly removes target during masked gap',async()=>{const{continuityCycle}=await import('../src/audio/core.js');const c=continuityCycle(1.2,.45,.25);assert.ok(c.some(s=>s.kind==='target'&&s.gain===0));assert.ok(c.some(s=>s.kind==='masker'&&s.gain>0));const gap=c.find(s=>s.kind==='target'&&s.gain===0);assert.equal(gap?.start,.45);assert.equal(gap?.duration,.25)});
