import {useEffect,useRef,useState,type KeyboardEvent as ReactKeyboardEvent} from 'react';
import {audioEngine} from '../audio/AudioEngine';
import {KEYBOARD_MAP,parseMidi,ccToBipolar,xyToBipolar,advancePhase,bipolar} from './core.js';
import {shepardFrame} from '../audio/core.js';
import './styles.css';

type Lanes={pitch:number;tempo:number;pan:number;distance:number;spectrum:number};
type LaneKey=keyof Lanes;
type Voice={partials:{o:OscillatorNode;g:GainNode}[];voiceGain:GainNode;filter:BiquadFilterNode;pan:StereoPannerNode;base:number;velocity:number};
const initial:Lanes={pitch:.35,tempo:.2,pan:.25,distance:-.1,spectrum:.4};
const factories:Record<string,Lanes>={'Coherent Rise':initial,'Opposed Space':{pitch:.38,tempo:.18,pan:.55,distance:-.48,spectrum:-.3},'Slow Spiral':{pitch:.08,tempo:.06,pan:.16,distance:.1,spectrum:.12},'Contradiction':{pitch:.6,tempo:-.42,pan:.7,distance:.55,spectrum:-.65}};
const PRESET_KEY='ail.motion.user-scene.v1',MIDI_KEY='ail.motion.midi-map.v1';

export function InfiniteMotionPage(){
  const [lanes,setLanes]=useState<Lanes>(initial),[linked,setLinked]=useState(true),[midi,setMidi]=useState('MIDI optional'),[hold,setHold]=useState(false),[preset,setPreset]=useState('Coherent Rise'),[learnTarget,setLearnTarget]=useState<LaneKey|null>(null);
  const lanesRef=useRef(lanes),voices=useRef(new Map<number,Voice>()),phases=useRef({pitch:0,tempo:0,pan:0,distance:0,spectrum:0}),raf=useRef(0),last=useRef(0),rhythmPhase=useRef(0),busRef=useRef<GainNode|null>(null),midiMap=useRef<Record<number,LaneKey>>({});
  useEffect(()=>{lanesRef.current=lanes},[lanes]);
  useEffect(()=>{try{midiMap.current=JSON.parse(localStorage.getItem(MIDI_KEY)||'{}')}catch{midiMap.current={}}},[]);
  const pulse=()=>{const ctx=audioEngine.context(),bus=busRef.current;if(!bus)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.value=95;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.035);o.connect(g).connect(bus);o.start();o.stop(ctx.currentTime+.04)};
  const updateAudio=(now:number)=>{if(!last.current)last.current=now;const dt=Math.min(.08,(now-last.current)/1000);last.current=now;const l=lanesRef.current;(['pitch','tempo','pan','distance','spectrum'] as LaneKey[]).forEach(k=>{phases.current[k]=advancePhase(phases.current[k],l[k]*.18,dt)});const pitchMod=bipolar(phases.current.pitch,Math.min(1,Math.abs(l.pitch))),panMod=bipolar(phases.current.pan,Math.min(1,Math.abs(l.pan))),distMod=bipolar(phases.current.distance,Math.min(1,Math.abs(l.distance))),specMod=bipolar(phases.current.spectrum,Math.min(1,Math.abs(l.spectrum)));const ctx=busRef.current?audioEngine.context():null;if(ctx){voices.current.forEach(v=>{const frame=shepardFrame(v.base/4,5,900*Math.pow(2,specMod*1.15),1.35,(pitchMod+1)/2,l.pitch<0?-1:1);frame.forEach((x:any,i:number)=>{v.partials[i].o.frequency.setTargetAtTime(Math.max(20,Math.min(18000,x.frequency)),ctx.currentTime,.018);v.partials[i].g.gain.setTargetAtTime(x.gain,ctx.currentTime,.025)});v.pan.pan.setTargetAtTime(panMod,ctx.currentTime,.03);v.filter.frequency.setTargetAtTime(Math.max(80,Math.min(18000,900+((specMod+1)/2)*9000-(distMod+1)*1200)),ctx.currentTime,.04);v.voiceGain.gain.setTargetAtTime((.035+.035*(1-distMod))*v.velocity,ctx.currentTime,.04)});const bpm=90*Math.pow(2,bipolar(phases.current.tempo,Math.min(1,Math.abs(l.tempo))));rhythmPhase.current+=dt*bpm/60;if(rhythmPhase.current>=1){rhythmPhase.current%=1;pulse()}}raf.current=requestAnimationFrame(updateAudio)};
  const ensureTick=()=>{if(!raf.current){last.current=0;raf.current=requestAnimationFrame(updateAudio)}};
  const noteOn=async(note:number,vel=.8)=>{if(voices.current.has(note))return;const ctx=await audioEngine.ensureRunning(),bus=await audioEngine.createInputBus();busRef.current=bus;const voiceGain=ctx.createGain(),filter=ctx.createBiquadFilter(),pan=ctx.createStereoPanner();filter.type='lowpass';filter.frequency.value=6500;voiceGain.gain.value=.045*vel;voiceGain.connect(filter).connect(pan).connect(bus);const base=440*Math.pow(2,(note-69)/12),frame=shepardFrame(base/4,5,900,1.35,0,1),partials=frame.map((x:any)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=Math.max(20,Math.min(18000,x.frequency));g.gain.value=x.gain;o.connect(g).connect(voiceGain);o.start();return{o,g}});voices.current.set(note,{partials,voiceGain,filter,pan,base,velocity:vel});ensureTick()};
  const noteOff=(note:number)=>{const v=voices.current.get(note);if(!v)return;const ctx=audioEngine.context();v.voiceGain.gain.setTargetAtTime(0,ctx.currentTime,.025);setTimeout(()=>{v.partials.forEach(({o,g})=>{try{o.stop()}catch{};o.disconnect();g.disconnect()});v.voiceGain.disconnect();v.filter.disconnect();v.pan.disconnect()},120);voices.current.delete(note)};
  const releaseAll=()=>{[...voices.current.keys()].forEach(noteOff);if(raf.current){cancelAnimationFrame(raf.current);raf.current=0}rhythmPhase.current=0};
  useEffect(()=>{const unregister=audioEngine.registerCleanup(releaseAll);return()=>{unregister();releaseAll()}},[]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select,button')||e.repeat)return;const n=KEYBOARD_MAP[e.code as keyof typeof KEYBOARD_MAP];if(n)void noteOn(n)};const up=(e:KeyboardEvent)=>{const n=KEYBOARD_MAP[e.code as keyof typeof KEYBOARD_MAP];if(n&&!hold)noteOff(n)};addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[hold]);
  const change=(k:LaneKey,v:number)=>setLanes(s=>linked?{pitch:v,tempo:v,pan:v,distance:v,spectrum:v}:{...s,[k]:v});
  useEffect(()=>{const nav=navigator as Navigator&{requestMIDIAccess?:()=>Promise<MIDIAccess>};if(!nav.requestMIDIAccess){setMidi('Web MIDI unavailable; keyboard fully supported');return}nav.requestMIDIAccess().then(access=>{const wire=()=>{access.inputs.forEach(input=>input.onmidimessage=e=>{const m=parseMidi(Array.from(e.data??[]));if(m.type==='noteon')void noteOn(m.note,m.velocity);if(m.type==='noteoff'&&!hold)noteOff(m.note);if(m.type==='cc'){if(learnTarget){midiMap.current[m.cc]=learnTarget;try{localStorage.setItem(MIDI_KEY,JSON.stringify(midiMap.current))}catch{}setLearnTarget(null);setMidi(`CC ${m.cc} learned for ${learnTarget}`)}else{const lane=midiMap.current[m.cc];if(lane)change(lane,ccToBipolar(m.value*127))}}})};wire();setMidi(`${access.inputs.size} MIDI input(s)`);access.onstatechange=()=>{wire();setMidi(`${access.inputs.size} MIDI input(s)`);if([...access.inputs.values()].some(i=>i.state==='disconnected'))releaseAll()}}).catch(()=>setMidi('MIDI permission not granted'))},[hold,learnTarget]);
  const applyPreset=(name:string)=>{let scene=factories[name];if(name==='User Scene'){try{scene=JSON.parse(localStorage.getItem(PRESET_KEY)||'null')||initial}catch{scene=initial}}if(scene){setLinked(false);setLanes(scene);setPreset(name)}};
  const saveScene=()=>{try{localStorage.setItem(PRESET_KEY,JSON.stringify(lanes));setPreset('User Scene')}catch{}};
  const toggleHold=()=>{const next=!hold;setHold(next);if(next)void noteOn(48,.75);else releaseAll()};
  const updateXY=(clientX:number,clientY:number,el:HTMLElement)=>{const r=el.getBoundingClientRect(),xy=xyToBipolar(clientX-r.left,clientY-r.top,r.width,r.height);setLinked(false);setLanes(s=>({...s,pitch:xy.x,spectrum:xy.y}))};
  const xyKey=(e:ReactKeyboardEvent<HTMLDivElement>)=>{const step=e.shiftKey?.2:.08;let p=lanes.pitch,s=lanes.spectrum;if(e.key==='ArrowLeft')p-=step;if(e.key==='ArrowRight')p+=step;if(e.key==='ArrowDown')s-=step;if(e.key==='ArrowUp')s+=step;if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setLinked(false);setLanes(v=>({...v,pitch:Math.max(-1,Math.min(1,p)),spectrum:Math.max(-1,Math.min(1,s))}))}};
  return <main className="motion-page"><section className="hero"><div><span className="eyebrow">EXPERIMENTAL INSTRUMENT</span><h1>Infinite Motion</h1><p>Cyclic pitch, tempo, space, distance and spectrum can move together or deliberately disagree.</p></div><div className="orb" style={{transform:`rotate(${lanes.pan*120}deg) scale(${1+lanes.distance*.15})`}}><i/><i/><i/></div></section><section className="motion-toolbar"><label>Scene <select value={preset} onChange={e=>applyPreset(e.target.value)}>{[...Object.keys(factories),'User Scene'].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={saveScene}>Save Current</button><button className={hold?'active':''} onClick={toggleHold}>{hold?'Release Hold':'Drone Hold'}</button><button onClick={()=>{releaseAll();audioEngine.panic()}}>Stop All</button></section><section className="motion-field" tabIndex={0} role="application" aria-label="XY macro: horizontal pitch motion, vertical spectral motion" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);updateXY(e.clientX,e.clientY,e.currentTarget)}} onPointerMove={e=>{if(e.buttons)updateXY(e.clientX,e.clientY,e.currentTarget)}} onKeyDown={xyKey}><div className="xy-dot" style={{left:`${(lanes.pitch+1)*50}%`,top:`${(1-lanes.spectrum)*50}%`}}/><span>PITCH MOTION →</span><b>SPECTRUM ↑</b></section><div className="matrix"><div className="matrix-head"><h2>Perceptual Contradiction Matrix</h2><button onClick={()=>{setLinked(true);setLanes(initial)}}>Restore coherent</button><label><input type="checkbox" checked={!linked} onChange={e=>setLinked(!e.target.checked)}/> Unlink cues</label></div>{(Object.entries(lanes) as [LaneKey,number][]).map(([k,v])=><div className="lane" key={k}><span>{k.toUpperCase()}</span><input aria-label={`${k} motion`} type="range" min="-1" max="1" step=".01" value={v} onChange={e=>change(k,+e.target.value)}/><output>{v.toFixed(2)}</output><button className={learnTarget===k?'active':''} onClick={()=>setLearnTarget(k)}>MIDI Learn</button></div>)}</div><section className="keyboard"><h2>Performance input</h2><p><kbd>A</kbd><kbd>W</kbd><kbd>S</kbd><kbd>E</kbd><kbd>D</kbd><kbd>F</kbd><kbd>T</kbd><kbd>G</kbd><kbd>Y</kbd><kbd>H</kbd><kbd>U</kbd><kbd>J</kbd><kbd>K</kbd></p><small>{learnTarget?`Move a MIDI CC to map ${learnTarget}. `:''}{midi}</small></section><p className="lab-note">Contradictory cue routing is an experimental sound-design system, not a canonical psychoacoustic demonstration.</p></main>}
